title: "Alexander Abiokorigh Samuel"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
 A Software Engineer, who is dedicated to helping clients accomplish technical goals by developing user friendly and forward-thinking apps.
 Experience working with Javascript Both Front-End And Back-End. With Frameworks Like, ReactJs, React-Native And NodeJs.
baseurl: "/sam-portfolio" 
url: "/portfolio-template" 
twitter_username: @abiokorigho
github_username:  alexzender45

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
